export const FETCH_COMING_SOON_SUCCESS = 'FETCH_COMING_SOON_SUCCESS'
export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS'
export const CHANGE_LEFTNAV_STATE = 'CHANGE_LEFTNAV_STATE'
export const CHANGE_CINEMA_STATE = 'CHANGE_CINEMA_STATE'
export const FETCH_CINEMA_SUCCESS = 'FETCH_CINEMA_SUCCESS'
export const FETCH_CINEMADETAIL_SUCCESS = 'FETCH_CINEMADETAIL_SUCCESS'


